- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpcName}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
        dns_hostnames: yes
        dns_support: yes
        state: "{{state}}"
      register: vpcout
  
    # - debug:
    #    var: vpcout
        
    - name: Create a Public Subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSubCidr1}}"
        az: "{{zone1}}"
        map_public: yes
        state: "{{state}}"
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out
      
    - name: Create a Public Subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSubCidr2}}"
        az: "{{zone2}}"
        map_public: yes
        state: "{{state}}"
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out
      
    - name: Create a Public Subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSubCidr3}}"
        az: "{{zone3}}"
        map_public: yes
        state: "{{state}}"
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out
      
    - name: Create a Private Subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSubCidr1}}"
        az: "{{zone1}}"
        map_public: no
        state: "{{state}}"
        resource_tags:
          Name: vprofile-privsub1
      register: privsub1_out
      
    - name: Create a Private Subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSubCidr2}}"
        az: "{{zone2}}"
        map_public: no
        state: "{{state}}"
        resource_tags:
          Name: vprofile-privsub2
      register: privsub2_out
      
    - name: Create a Private Subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSubCidr3}}"
        az: "{{zone3}}"
        map_public: no
        state: "{{state}}"
        resource_tags:
          Name: vprofile-privsub3
      register: privsub3_out
      
    - name: create the Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
          Name: vprofile-IGW
      register: vprofile_igw_out
        
      
